version: "3.8"

services:
  portfolio-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      # Server Configuration
      SERVER_PORT: ${SERVER_PORT:-8080}
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}

      # Database Configuration
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-myapi}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-your_secret_key_here}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your_refresh_secret_key_here}
      JWT_EXPIRED_AT: ${JWT_EXPIRED_AT:-10m}
      JWT_REFRESH_EXPIRED_AT: ${JWT_REFRESH_EXPIRED_AT:-7d}
    volumes:
      - ./uploads:/app/uploads
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "/app/main", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  portfolio-network:
    driver: bridge
